image: 
- Visual Studio 2017
install:
- pip install flask
- pip install Flask-Testing
- pip install master.models
- pip install master.master
- pip install apscheduler.jobstores.memory
- pip install apscheduler.executors.pool
test_script:
- python tests/__init__.py

build: off
